image: "python:3.5"

before_script:
  - python --version
  - pip install tqdm cmocean numpy scipy pytest pytest-flake8

stages:
  - test

test:
  stage: test
  script:
    - python setup.py build
    - py.test --flake8


