image: "python:3.5"

stages:
  - test

test:
  stage: test
  script:
  - virtualenv jutil-env
  - source ./jutil-env/bin/activate
  - pip install scipy numpy nose pytest-cov pytest-flake8 coverage tqdm pytest-runner
  - python setup.py build
  - py.test jutil
